# Generated by Django 4.2.2 on 2023-07-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AJ', 'آجیل مخلوط'), ('PE', 'پسته'), ('BA', 'بادام'), ('GE', 'گردو'), ('FA', 'فندق'), ('TO', 'تخمه'), ('NO', 'نخود')], max_length=2),
        ),
    ]
