# Generated by Django 4.2.2 on 2023-07-02 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.ImageField(upload_to='')),
                ('zipcode', models.ImageField(upload_to='')),
                ('state', models.CharField(choices=[('تهران', 'تهران'), ('مشهد', 'مشهد'), ('اصفهان', 'اصفهان'), ('شیراز', 'شیراز'), ('تبریز', 'تبریز'), ('کرج', 'کرج'), ('اهواز', 'اهواز'), ('کرمانشاه', 'کرمانشاه'), ('ارومیه', 'ارومیه'), ('رشت', 'رشت'), ('زاهدان', 'زاهدان'), ('همدان', 'همدان'), ('کرمان', 'کرمان'), ('یزد', 'یزد'), ('اردبیل', 'اردبیل'), ('بندرعباس', 'بندرعباس'), ('اراک', 'اراک'), ('اسلامشهر', 'اسلامشهر'), ('زنجان', 'زنجان'), ('سنندج', 'سنندج'), ('قزوین', 'قزوین'), ('خرم\u200cآباد', 'خرم\u200cآباد'), ('گرگان', 'گرگان'), ('ساری', 'ساری'), ('آبادان', 'آبادان'), ('ورامین', 'ورامین'), ('شهرکرد', 'شهرکرد'), ('سمنان', 'سمنان'), ('مرودشت', 'مرودت'), ('زابل', 'زابل'), ('یاسوج', 'یاسوج'), ('خرمشهر', 'خرمشهر'), ('بم', 'بم'), ('بانه', 'بانه'), ('چابهار', 'چابهار'), ('لاهیجان', 'لاهیجان'), ('چالوس', 'چالوس')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
