# Generated by Django 4.2.2 on 2023-07-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_mobile_alter_customer_zipcode_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
    ]
